// src/routes/+page.svelte
<script lang='ts'>
  import { getSelections } from '$lib/api/discovery.remote'
  import Button from '$lib/components/Button.svelte'
  import PlaylistListing from '$lib/components/listings/PlaylistListing.svelte'
  import Main from '$lib/components/Main.svelte'
  import Spinner from '$lib/components/Spinner.svelte'
</script>

<Main>
  <div class='my-16 flex flex-col gap-4'>
    <h1 class='mx-auto text-center text-3xl font-mediums'>Sveltrum</h1>
    <div class='flex gap-4 justify-center'>
      <Button href='https://tijn.dev/sveltrum'>View on GitHub</Button>
    </div>
  </div>

  <h2 class='text-2xl font-medium'>Trending playlists</h2>

  {#await getSelections()}
    <Spinner />
  {:then selections}
    {#each selections as selection}
      {#each selection.items.collection as playlist}
        <PlaylistListing playlist={playlist} />
      {/each}
    {/each}
  {/await}
</Main>

// src/routes/index.tsx
import { createFileRoute } from "@tanstack/react-router";
import { Button } from "../lib/components/button";
import { PlaylistListing } from "../lib/components/listings/playlist-listing";
import { Main } from "../lib/components/main";
import { getSelections } from "../lib/server-functions/discovery";

export const Route = createFileRoute("/")({
	component: RouteComponent,
	loader: () => getSelections(),
});

function RouteComponent() {
	const selections = Route.useLoaderData();

	return (
		<Main>
			<div className="my-16 flex flex-col gap-4">
				<h1 className="mx-auto text-center font-mediums text-3xl">Sveltrum</h1>
				<div className="flex justify-center gap-4">
					<Button href="https://tijn.dev/sveltrum">View on GitHub</Button>
				</div>
			</div>

			<h2 className="font-medium text-2xl">Trending playlists</h2>

			{selections.length ? (
				selections.map((selection) =>
					selection.items.collection.map((playlist) => (
						<PlaylistListing key={playlist.id} playlist={playlist} />
					)),
				)
			) : (
				<span className="mt-4 text-lg text-zinc-100/25">Nothing here...</span>
			)}
		</Main>
	);
}
