// src/lib/components/ui/Button.svelte
<script module lang="ts">
	import type { ButtonRootProps } from 'bits-ui'
	import { tv, type VariantProps } from 'tailwind-variants'

	export const buttonVariants = tv({
		slots: {
			base: [
				'flex cursor-pointer items-center justify-center gap-2 rounded-full transition-transform',
				'active:scale-90 active:opacity-50',
			],
		},
		variants: {
			variant: {
				primary: 'bg-white text-zinc-800',
				secondary: 'bg-zinc-700',
			},
			size: {
				default: 'px-4 py-2',
				icon: 'size-10',
			},
		},
		defaultVariants: {
			size: 'default',
			variant: 'primary',
		},
	})

	export type ButtonProps = ButtonRootProps &
		VariantProps<typeof buttonVariants> & {
			icon?: Component<IconProps>
		}
</script>

<script lang="ts">
	import type { IconProps } from '@lucide/svelte'
	import { Button } from 'bits-ui'
	import { cn } from 'cnfn'
	import type { Component } from 'svelte'

	const {
		children,
		variant,
		size,
		icon: Icon,
		class: className,
		...props
	}: ButtonProps = $props()

	const classes = $derived(buttonVariants({ variant, size }))
</script>

<Button.Root class={classes.base({ class: cn(className) })} {...props}>
	{#if Icon}
		<Icon size={16} strokeWidth={3} class="shrink-0" />
	{/if}

	{@render children?.()}
</Button.Root>

// src/components/Button.tsx
import { Slot } from '@radix-ui/react-slot'
import { cn } from 'cnfn'
import type { ComponentProps } from 'react'
import { tv, type VariantProps } from 'tailwind-variants'

export const buttonVariants = tv({
	slots: {
		base: 'flex items-center cursor-pointer justify-center gap-2 rounded-full transition-transform active:scale-90 active:opacity-50',
	},
	variants: {
		variant: {
			primary: 'bg-white text-zinc-800',
			secondary: 'bg-zinc-100/10',
		},
		size: {
			default: 'h-9 px-4',
			icon: 'size-10',
		},
	},
	defaultVariants: {
		variant: 'primary',
		size: 'default',
	},
})

export interface ButtonProps extends ComponentProps<'button'> {
	variant?: VariantProps<typeof buttonVariants>['variant']
	size?: VariantProps<typeof buttonVariants>['size']
	asChild?: boolean
}

export function Button({
	className,
	variant,
	size,
	asChild = false,
	...props
}: ButtonProps) {
	const Comp = asChild ? Slot : 'button'

	const classes = buttonVariants({ variant, size, className })

	return <Comp data-slot='button' className={cn(classes.base())} {...props} />
}
