// src/lib/components/HeroSection.svelte
<script module lang='ts'>
  import type { User } from '$lib/schemas/user'

  export interface HeroSectionProps {
    pictureSrc?: string | null
    title: string
    user?: User
    roundedPicture?: boolean
  }
</script>

<script lang='ts'>
  import { cn } from 'cnfn'
  import UserListing from './listings/UserListing.svelte'

  const { pictureSrc, title, user, roundedPicture = false }: HeroSectionProps = $props()
</script>

{#if pictureSrc}
  <img
    src={pictureSrc.replace('large', 't500x500')}
    class={cn('mx-auto my-4 w-full max-w-xs aspect-square', roundedPicture ? 'rounded-full' : 'rounded-xl')}
    alt=""
  />
{/if}

<h1 class='font-medium text-2xl'>{title}</h1>
{#if user}
  <UserListing user={user} class='mt-4' />
{/if}

// src/lib/components/HeroSection.tsx
import { cn } from "cnfn";
import type { User } from "../schemas/user";
import { UserListing } from "./listings/UserListing";

export interface HeroSectionProps {
	pictureSrc?: string | null;
	title: string;
	user?: User;
	roundedPicture?: boolean;
}

export function HeroSection({
	pictureSrc,
	title,
	user,
	roundedPicture = false,
}: HeroSectionProps) {
	return (
		<>
			{!!pictureSrc && (
				<img
					src={pictureSrc.replace("large", "t500x500")}
					className={cn(
						"mx-auto my-4 aspect-square w-full max-w-xs",
						roundedPicture ? "rounded-full" : "rounded-xl",
					)}
					alt={title}
				/>
			)}

			<h1 className="font-medium text-2xl">{title}</h1>

			{!!user && <UserListing user={user} className="mt-4" />}
		</>
	);
}
