// src/lib/components/ListingThumbnail.svelte
<script module lang='ts'>
  import type { ClassValue } from 'cnfn'

  export interface ListingThumbnailProps {
    src?: string | null
    alt: string
    class?: ClassValue
  }
</script>

<script lang='ts'>
  import { cn } from 'cnfn'

  const { src, alt, ...props }: ListingThumbnailProps = $props()

  let hasFailed = $state(false)
</script>

{#if src && !hasFailed}
  <img {src} {alt} class={cn('rounded size-12 aspect-square', props.class)} onerror={() => hasFailed = true}>
{:else}
  <div class='bg-zinc-700 rounded size-12 aspect-square'></div>
{/if}

// src/lib/components/listing-thumbnail.tsx
import { type ClassValue, cn } from "cnfn";
import { useState } from "react";

export interface ListingThumbnailProps {
	src?: string | null;
	alt: string;
	class?: ClassValue;
}

export function ListingThumbnail({
	src,
	alt,
	...props
}: ListingThumbnailProps) {
	const [hasFailed, setHasFailed] = useState(false);

	return src && !hasFailed ? (
		<img
			src={src}
			alt={alt}
			className={cn("aspect-square size-12 rounded", props.class)}
			onError={() => setHasFailed(true)}
		/>
	) : (
		<div className="aspect-square size-12 rounded bg-zinc-700"></div>
	);
}
