// src/lib/components/listings/UserListing.svelte
<script module lang="ts">
	import type { User } from '$lib/schemas/user'
	import type { ClassValue } from 'cnfn'

	export interface UserListingProps {
		user: User
		class?: ClassValue
	}
</script>

<script lang="ts">
	import ListingThumbnail from '../ListingThumbnail.svelte'
	import { cn } from 'cnfn'

	const { user, ...props }: UserListingProps = $props()
</script>

<a
	href="/{user.permalink}"
	class={cn(
		'grid grid-cols-[auto_1fr] items-center gap-4 text-left transition-transform active:scale-95 active:opacity-50',
		props.class,
	)}
>
	<ListingThumbnail
		src={user.avatar_url}
		alt="Profile picture of {user.username}"
		class="rounded-full"
	/>
	<div class="flex w-full min-w-0 flex-col">
		<h3 class="truncate">{user.username}</h3>
		{#if user.full_name !== user.username}
			<p class="truncate opacity-50">{user.full_name}</p>
		{/if}
	</div>
</a>

// src/lib/components/listings/user-listing.tsx
import { type ClassValue, cn } from "cnfn";
import type { User } from "../../schemas/user";
import { ListingThumbnail } from "../listing-thumbnail";

export interface UserListingProps {
	user: User;
	className?: ClassValue;
}

export function UserListing({ user, className }: UserListingProps) {
	return (
		<a
			href="/user/{user.id}"
			className={cn(
				"grid grid-cols-[auto_1fr] items-center gap-4 text-left transition-transform active:scale-95 active:opacity-50",
				className,
			)}
		>
			<ListingThumbnail
				src={user.avatar_url}
				alt="Profile picture of {user.username}"
				class="rounded-full"
			/>
			<div className="flex w-full min-w-0 flex-col">
				<h3 className="truncate">{user.username}</h3>
				{user.full_name !== user.username && (
					<p className="truncate opacity-50">{user.full_name}</p>
				)}
			</div>
		</a>
	);
}
